apiVersion: v1
kind: Namespace
metadata:
  name: kubelab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
  namespace: kubelab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cluster-admin
    namespace: kubelab
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: jupyterkubelab
  name: jupyterkubelab
  namespace: kubelab
spec:
  serviceAccountName: cluster-admin
  containers:
  - image: mjbright/jupyterkubelab:1.16.8
    name: jupyterkubelab
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
    volumeMounts:
    - mountPath: /root/.kube/config
      subPath: config
      name: kube-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Equal
    effect: NoSchedule
  #- key: node-role.kubernetes.io/master
  #  operator: Equal
  #  value: "true"
  #  effect: NoSchedule
  volumes:
  - name: kube-config
    configMap:
      name: kube-configmap
      items:
      - key: config.kubelab
        path: config
