apiVersion: v1
kind: Namespace
metadata:
  name: kubelab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
  namespace: kubelab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cluster-admin
    namespace: kubelab
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubelab
  name: kubelab
  namespace: kubelab
spec:
  serviceAccountName: cluster-admin
  containers:
  - image: mjbright/kubelab:1.18.0
    name: kubelab
    volumeMounts:
    - mountPath: /root/.kube/config
      subPath: config
      name: kube-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: kube-config
    configMap:
      name: kube-configmap
      items:
      - key: config.kubelab
        path: config

